server:
  port: 1010
  
spring:
  application:
    name: donor-service
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: hr
    password: hr
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    shutdown:
      enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
info:
   build:
    artificatId: '@project.artifact@'
    groupId: '@project.groupid@'
   java:
     version: 8.0



